<?php
/**
 * Admin -> Products -> add/edit form. One big form covering the product's
 * core fields, price/tax entry, discount scheduling, an availability
 * window, legal/warranty fields, image management (linked out, not
 * inline), and up to two option groups (e.g. "Size"/"Color") with their
 * generated stock-tracked variant combinations. Same create-vs-edit
 * pattern as the simpler admin pages: $id is null and $product is null
 * when creating; both are set when editing.
 *
 * IMPORTANT (see CLAUDE.md's "Product/option translation" section):
 * product_options/product_option_values are fully DELETED and RECREATED
 * on every save, so this form's translation inputs for every enabled
 * language are always rendered into the page (just CSS-hidden for
 * inactive language tabs, never removed from the DOM) so they always
 * resubmit and get re-inserted - if that stopped being true, saving a
 * product without touching an inactive language tab would silently wipe
 * that language's translations.
 *
 * @var int|null   $id                       The product's id, or null when creating a new product (nothing to edit-link to yet, e.g. images).
 * @var array|null $product                  The product row being edited (default-language content only - translations live separately, see $productTranslations), or null when creating.
 * @var array      $options                  Up to two existing option groups (each with a 'name' and a 'values' list) already saved for this product, prefilled into the "Options" fieldset below.
 * @var array      $variantStockByCombo      Map of "combo key" (option values joined by '||') => current stock quantity, used to seed the variant stock inputs generated by JS on page load.
 * @var array      $categories               Every category, flattened with a 'depth' key, for the category dropdown.
 * @var array      $availableLangs           Enabled languages as [code => label], for the per-language tabs.
 * @var string     $defaultLang              The shop's default/primary language - its fields are the real product/product_options columns; every other language is a translation overlay (see CLAUDE.md).
 * @var array      $otherLanguages           $availableLangs minus $defaultLang (kept as a separate variable for convenience, even though most loops below just filter $availableLangs by comparing to $defaultLang directly).
 * @var array      $productTranslations      Existing translated name/short_description/description per language code, for the non-default-language tabs.
 * @var array      $optionTranslationsForForm Existing translated option names/values per language code and option-row index, for the non-default-language tabs of the "Options" fieldset.
 * @var array      $taxRates                 Every configured tax rate, for the tax-rate dropdown (only shown when $vatEnabled).
 * @var bool       $vatEnabled               Whether the shop charges VAT at all - see vatIsEnabled() elsewhere; hides tax-related fields entirely when false.
 * @var array      $errors                   Validation error messages to show above the form.
 * Direct port of admin/product_edit.php's body.
 */
// One form action handles both create and edit - POSTing to .../create vs
// .../{id}/edit is how the controller tells the two cases apart (there's
// no hidden "id" input like the simpler admin pages use for this).
$actionUrl = rtrim(SITE_URL, '/') . '/admin/products' . ($id ? '/' . $id . '/edit' : '/create');
?>
<div class="page-header"><h1><?= e($pageTitle) ?></h1></div>
<?php foreach ($errors as $error): ?><div class="flash flash-error"><?= e($error) ?></div><?php endforeach; ?>

<form method="post" action="<?= e($actionUrl) ?>">
  <?= csrfField() ?>
  <div class="card">
    <div class="form-group"><label for="sku"><?= e(__('admin.dashboard.sku')) ?></label><input type="text" id="sku" name="sku" required value="<?= e($product['sku'] ?? '') ?>"></div>

    <?php /* Tab buttons only needed when there's more than one language to switch between - clicking one is pure client-side JS (see the "lang-tab-btn" script further down), no page reload. */ ?>
    <?php if (count($availableLangs) > 1): ?>
      <div class="lang-tabs" role="tablist">
        <?php foreach ($availableLangs as $code => $label): ?>
          <button type="button" class="btn btn-sm lang-tab-btn <?= $code === $defaultLang ? '' : 'btn-secondary' ?>" data-lang-tab="<?= e($code) ?>"><?= e($label) ?></button>
        <?php endforeach; ?>
      </div>
    <?php endif; ?>

    <?php /* One panel per enabled language, all rendered into the page at once - only the default language's panel starts visible (the others are display:none, NOT removed from the DOM), so every language's inputs still submit with the form regardless of which tab was showing when Save was clicked. This is what makes the "always resubmit every language" behavior described in this file's top docblock work. */ ?>
    <?php foreach ($availableLangs as $code => $label): ?>
      <div data-lang-panel="<?= e($code) ?>" <?= $code === $defaultLang ? '' : 'style="display:none;"' ?>>
        <?php /* Default language writes straight to the product's own name/short_description/description columns; every other language writes to the *_translations[$code] arrays instead, which the controller uses to update the separate product_translations table (see CLAUDE.md's "Product/option translation" section). */ ?>
        <?php if ($code === $defaultLang): ?>
          <div class="form-group"><label for="name"><?= e(__('admin.products.name')) ?></label><input type="text" id="name" name="name" required value="<?= e($product['name'] ?? '') ?>"></div>
          <div class="form-group"><label for="short_description"><?= e(__('admin.product_edit.short_description')) ?></label><input type="text" id="short_description" name="short_description" value="<?= e($product['short_description'] ?? '') ?>"></div>
          <div class="form-group"><label for="description"><?= e(__('product.description')) ?></label><textarea id="description" name="description" rows="4"><?= e($product['description'] ?? '') ?></textarea></div>
        <?php else: ?>
          <p style="color:var(--color-muted);font-size:13px;margin-top:0;"><?= e(__('admin.product_edit.translation_hint', ['lang' => $availableLangs[$defaultLang]])) ?></p>
          <div class="form-group">
            <label for="name_translations_<?= e($code) ?>"><?= e(__('admin.products.name')) ?></label>
            <input type="text" id="name_translations_<?= e($code) ?>" name="name_translations[<?= e($code) ?>]" value="<?= e($productTranslations[$code]['name'] ?? '') ?>">
          </div>
          <div class="form-group">
            <label for="short_description_translations_<?= e($code) ?>"><?= e(__('admin.product_edit.short_description')) ?></label>
            <input type="text" id="short_description_translations_<?= e($code) ?>" name="short_description_translations[<?= e($code) ?>]" value="<?= e($productTranslations[$code]['short_description'] ?? '') ?>">
          </div>
          <div class="form-group">
            <label for="description_translations_<?= e($code) ?>"><?= e(__('product.description')) ?></label>
            <textarea id="description_translations_<?= e($code) ?>" name="description_translations[<?= e($code) ?>]" rows="4"><?= e($productTranslations[$code]['description'] ?? '') ?></textarea>
          </div>
        <?php endif; ?>
      </div>
    <?php endforeach; ?>

    <div class="form-grid">
      <div class="form-group">
        <label for="category_id"><?= e(__('admin.products.category')) ?></label>
        <select id="category_id" name="category_id">
          <option value="">-- <?= e(__('common.none')) ?> --</option>
          <?php foreach ($categories as $cat): ?>
            <option value="<?= (int)$cat['id'] ?>" <?= (($product['category_id'] ?? null) == $cat['id']) ? 'selected' : '' ?>>
              <?= str_repeat('&mdash; ', $cat['depth']) ?><?= e($cat['name']) ?>
            </option>
          <?php endforeach; ?>
        </select>
      </div>
      <div class="form-group">
        <label for="status"><?= e(__('common.status')) ?></label>
        <select id="status" name="status">
          <?php foreach (['active', 'draft', 'archived'] as $s): ?>
            <option value="<?= $s ?>" <?= (($product['status'] ?? 'active') === $s) ? 'selected' : '' ?>><?= e(__('admin.product_edit.status_' . $s)) ?></option>
          <?php endforeach; ?>
        </select>
      </div>
    </div>
    <?php
    // --- Figuring out what to prefill into the price/tax fieldset below ---
    // A brand-new product (no tax_rate_id saved yet) defaults to whichever
    // tax rate is marked "is_default" in Settings, rather than leaving the
    // dropdown on an arbitrary first option.
    $currentTaxRateId = $product['tax_rate_id'] ?? null;
    if ($currentTaxRateId === null) {
        foreach ($taxRates as $tr) {
            if ($tr['is_default']) { $currentTaxRateId = $tr['id']; break; }
        }
    }
    // price_entry_mode remembers whether this product's price was last
    // typed in as "net" (excl. tax) or "gross" (incl. tax) - purely a UI
    // convenience so re-opening the form shows the same kind of number the
    // admin originally typed, not a stored pricing policy.
    $currentMode = $product['price_entry_mode'] ?? 'net';
    $currentRatePercent = 0.0;
    foreach ($taxRates as $tr) {
        if ((int)$tr['id'] === (int)$currentTaxRateId) $currentRatePercent = (float)$tr['rate'];
    }
    // The product's price is ALWAYS stored net (excl. tax) in the database
    // (see 'price' column) - if the admin last entered it as gross, this
    // converts back to gross just for prefilling the form field, so the
    // number displayed matches what they originally typed rather than
    // silently swapping to the stored net figure.
    $prefillPrice = '';
    if (isset($product['price'])) {
        $prefillPrice = $currentMode === 'gross' && $currentRatePercent > 0
            ? round((float)$product['price'] * (1 + $currentRatePercent / 100), 2)
            : (float)$product['price'];
    }
    ?>
    <fieldset style="margin:0 0 16px;">
      <legend style="font-size:15px;"><?= e(__('common.price')) ?><?= $vatEnabled ? ' &amp; ' . e(__('common.tax')) : '' ?></legend>
      <?php /* Lets the admin type EITHER the net or the gross price, whichever they know off-hand (e.g. copying a competitor's displayed price, which is gross) - the controller converts back to net for storage using $prefillPrice's same math. When VAT is disabled shop-wide there's no tax to convert, so the mode is hard-locked to "net" via a hidden field instead of offering a meaningless choice. */ ?>
      <?php if ($vatEnabled): ?>
        <div class="form-group">
          <label><?= e(__('admin.product_edit.enter_price_as')) ?></label>
          <label style="font-weight:normal;margin-right:16px;"><input type="radio" name="price_entry_mode" value="net" <?= $currentMode !== 'gross' ? 'checked' : '' ?> style="width:auto;" onchange="syncPriceMode()"> <?= e(__('admin.product_edit.price_net')) ?></label>
          <label style="font-weight:normal;"><input type="radio" name="price_entry_mode" value="gross" <?= $currentMode === 'gross' ? 'checked' : '' ?> style="width:auto;" onchange="syncPriceMode()"> <?= e(__('admin.product_edit.price_gross')) ?></label>
        </div>
      <?php else: ?>
        <input type="hidden" name="price_entry_mode" value="net">
      <?php endif; ?>
      <div class="form-grid">
        <div class="form-group">
          <label for="price_input"><?= e(__('common.price')) ?></label>
          <input type="number" step="0.01" id="price_input" name="price_input" required value="<?= e($prefillPrice) ?>" oninput="syncPriceMode()">
          <small id="priceConversionHint" style="color:var(--color-muted);"></small>
        </div>
        <?php if ($vatEnabled): ?>
          <div class="form-group">
            <label for="tax_rate_id"><?= e(__('admin.product_edit.tax_rate')) ?></label>
            <select id="tax_rate_id" name="tax_rate_id" onchange="syncPriceMode()">
              <?php foreach ($taxRates as $tr): ?>
                <option value="<?= (int)$tr['id'] ?>" data-rate="<?= e($tr['rate']) ?>" <?= (int)$currentTaxRateId === (int)$tr['id'] ? 'selected' : '' ?>>
                  <?= e($tr['name']) ?> (<?= e($tr['rate']) ?>%)<?= $tr['is_default'] ? ' - ' . e(__('admin.product_edit.default')) : '' ?>
                </option>
              <?php endforeach; ?>
            </select>
          </div>
        <?php endif; ?>
      </div>
    </fieldset>
    <div class="form-grid">
      <div class="form-group"><label for="stock_quantity"><?= e(__('admin.product_edit.stock_quantity')) ?></label><input type="number" id="stock_quantity" name="stock_quantity" value="<?= e($product['stock_quantity'] ?? '0') ?>"></div>
      <div class="form-group"><label for="stock_threshold"><?= e(__('admin.product_edit.stock_threshold')) ?></label><input type="number" id="stock_threshold" name="stock_threshold" value="<?= e($product['stock_threshold'] ?? '5') ?>"></div>
    </div>
    <div class="form-grid">
      <div class="form-group">
        <label for="max_order_quantity"><?= e(__('admin.product_edit.max_order_quantity')) ?></label>
        <input type="number" id="max_order_quantity" name="max_order_quantity" min="1" value="<?= e($product['max_order_quantity'] ?? '') ?>" placeholder="<?= e(__('admin.product_edit.max_order_quantity_placeholder')) ?>">
        <small style="color:var(--color-muted);"><?= e(__('admin.product_edit.max_order_quantity_hint')) ?></small>
      </div>
      <div class="form-group"><label for="weight_kg"><?= e(__('admin.product_edit.weight_kg')) ?></label><input type="number" step="0.01" id="weight_kg" name="weight_kg" value="<?= e($product['weight_kg'] ?? '') ?>"></div>
    </div>
  </div>

  <script>
    // Live preview only - shows "= X (gross/net)" under the price field as
    // the admin types, so they can see the other figure without submitting
    // the form. The actual net/gross conversion used for STORAGE happens
    // server-side (mirroring $prefillPrice's math above) - this JS never
    // writes into any form field, it only updates the on-screen hint text.
    var grossSuffixTpl = <?= json_encode(__('admin.product_edit.gross_incl_vat')) ?>;
    var netSuffix = <?= json_encode(__('admin.product_edit.net')) ?>;
    function syncPriceMode() {
      var priceInput = document.getElementById('price_input');
      var hint = document.getElementById('priceConversionHint');
      var modeInput = document.querySelector('input[name="price_entry_mode"]:checked');
      var mode = modeInput ? modeInput.value : 'net';
      var rateSelect = document.getElementById('tax_rate_id');
      var rate = rateSelect ? parseFloat(rateSelect.options[rateSelect.selectedIndex].dataset.rate || '0') : 0;
      var amount = parseFloat(priceInput.value || '0');
      if (!rate || !amount) { hint.textContent = ''; return; }
      if (mode === 'net') {
        hint.textContent = '= ' + (amount * (1 + rate / 100)).toFixed(2) + ' ' + grossSuffixTpl.replace('{rate}', rate);
      } else {
        hint.textContent = '= ' + (amount / (1 + rate / 100)).toFixed(2) + ' ' + netSuffix;
      }
    }
    document.addEventListener('DOMContentLoaded', syncPriceMode);
  </script>

  <script>
    // Purely cosmetic tab-switching: shows the clicked language's panel(s)
    // (note this also toggles the per-language option-name/value panels
    // inside the "Options" fieldset further down, since they share the
    // same [data-lang-panel] attribute) and hides the rest. Every panel's
    // inputs stay in the DOM and still get submitted regardless of which
    // one is visible - see the note in this file's top docblock.
    document.querySelectorAll('.lang-tab-btn').forEach(function (btn) {
      btn.addEventListener('click', function () {
        var lang = btn.dataset.langTab;
        document.querySelectorAll('.lang-tab-btn').forEach(function (b) {
          b.classList.toggle('btn-secondary', b.dataset.langTab !== lang);
        });
        document.querySelectorAll('[data-lang-panel]').forEach(function (panel) {
          panel.style.display = (panel.dataset.langPanel === lang) ? '' : 'none';
        });
      });
    });
  </script>

  <?php /* A discount can be scheduled (starts_at/ends_at optional) - whether it's actually "live" right now (vs. scheduled for later or already expired) is computed on read by Services\DiscountCalculator, e.g. for the badge shown on the products list page and the price shown on the storefront - saving this form doesn't itself judge whether the discount is currently active. */ ?>
  <fieldset>
    <legend><?= e(__('admin.product_edit.discount')) ?></legend>
    <p style="color:var(--color-muted);font-size:13px;margin-top:0;">
      <?= e(__('admin.product_edit.discount_hint')) ?>
    </p>
    <div class="form-grid">
      <div class="form-group">
        <label for="discount_type"><?= e(__('admin.product_edit.discount_type')) ?></label>
        <select id="discount_type" name="discount_type">
          <option value="none" <?= (($product['discount_type'] ?? 'none') === 'none') ? 'selected' : '' ?>><?= e(__('common.none')) ?></option>
          <option value="percent" <?= (($product['discount_type'] ?? '') === 'percent') ? 'selected' : '' ?>><?= e(__('admin.product_edit.discount_percent')) ?></option>
          <option value="fixed" <?= (($product['discount_type'] ?? '') === 'fixed') ? 'selected' : '' ?>><?= e(__('admin.product_edit.discount_fixed')) ?></option>
        </select>
      </div>
      <div class="form-group"><label for="discount_value"><?= e(__('admin.product_edit.discount_value')) ?></label><input type="number" step="0.01" id="discount_value" name="discount_value" value="<?= e($product['discount_value'] ?? '') ?>"></div>
    </div>
    <div class="form-grid">
      <?php /* MySQL stores datetimes as "Y-m-d H:i:s" but an HTML <input type="datetime-local"> needs "Y-m-dTH:i" - substr(...,0,16) drops the seconds and str_replace swaps the space for a "T" to match what the browser control expects. */ ?>
      <div class="form-group">
        <label for="discount_starts_at"><?= e(__('admin.product_edit.discount_starts')) ?></label>
        <input type="datetime-local" id="discount_starts_at" name="discount_starts_at" value="<?= e(isset($product['discount_starts_at']) ? str_replace(' ', 'T', substr((string)$product['discount_starts_at'], 0, 16)) : '') ?>">
      </div>
      <div class="form-group">
        <label for="discount_ends_at"><?= e(__('admin.product_edit.discount_ends')) ?></label>
        <input type="datetime-local" id="discount_ends_at" name="discount_ends_at" value="<?= e(isset($product['discount_ends_at']) ? str_replace(' ', 'T', substr((string)$product['discount_ends_at'], 0, 16)) : '') ?>">
      </div>
    </div>
  </fieldset>

  <?php /* Independent of the discount window above: this controls whether the product is purchasable/visible on the storefront at all (e.g. a seasonal item), whereas discount dates just control pricing on an already-available product. Checked by \ShopRex\Models\Product::isRowCurrentlyAvailable() (used on the products list page and the storefront). */ ?>
  <fieldset>
    <legend><?= e(__('admin.product_edit.availability_window')) ?></legend>
    <p style="color:var(--color-muted);font-size:13px;margin-top:0;">
      <?= e(__('admin.product_edit.availability_window_hint')) ?>
    </p>
    <div class="form-grid">
      <div class="form-group">
        <label for="available_from"><?= e(__('admin.product_edit.available_from')) ?></label>
        <input type="datetime-local" id="available_from" name="available_from" value="<?= e(isset($product['available_from']) ? str_replace(' ', 'T', substr((string)$product['available_from'], 0, 16)) : '') ?>">
      </div>
      <div class="form-group">
        <label for="available_until"><?= e(__('admin.product_edit.available_until')) ?></label>
        <input type="datetime-local" id="available_until" name="available_until" value="<?= e(isset($product['available_until']) ? str_replace(' ', 'T', substr((string)$product['available_until'], 0, 16)) : '') ?>">
      </div>
    </div>
  </fieldset>

  <?php /* These fields feed the legal/compliance domain (RMA tickets and withdrawal requests - see CLAUDE.md's "New legal/compliance domain" section), not just informational display text. */ ?>
  <fieldset>
    <legend><?= e(__('admin.product_edit.legal_legend')) ?></legend>
    <p style="color:var(--color-muted);font-size:13px;margin-top:0;"><?= e(__('admin.product_edit.legal_hint')) ?></p>
    <?php /* statutory_warranty_months feeds RmaTicket::isEligible()'s warranty-length check (defaults to 24, the EU statutory minimum); manufacturer_warranty_months is a separate, optional, typically-longer warranty some products carry on top of that. */ ?>
    <div class="form-grid">
      <div class="form-group">
        <label for="statutory_warranty_months"><?= e(__('admin.product_edit.statutory_warranty_months')) ?></label>
        <input type="number" min="0" id="statutory_warranty_months" name="statutory_warranty_months" value="<?= e($product['statutory_warranty_months'] ?? '24') ?>">
      </div>
      <div class="form-group">
        <label for="manufacturer_warranty_months"><?= e(__('admin.product_edit.manufacturer_warranty_months')) ?></label>
        <input type="number" min="0" id="manufacturer_warranty_months" name="manufacturer_warranty_months" value="<?= e($product['manufacturer_warranty_months'] ?? '') ?>" placeholder="<?= e(__('admin.product_edit.manufacturer_warranty_placeholder')) ?>">
      </div>
    </div>
    <div class="form-group">
      <label for="manufacturer_warranty_notes"><?= e(__('admin.product_edit.manufacturer_warranty_notes')) ?></label>
      <input type="text" id="manufacturer_warranty_notes" name="manufacturer_warranty_notes" value="<?= e($product['manufacturer_warranty_notes'] ?? '') ?>">
    </div>
    <div class="form-group">
      <label><input type="checkbox" name="contains_battery" value="1" style="width:auto;" <?= !empty($product['contains_battery']) ? 'checked' : '' ?>> <?= e(__('admin.product_edit.contains_battery')) ?></label>
    </div>
    <?php /* Hygiene products (e.g. cosmetics, underwear) can be legally excluded per-item from the right-of-withdrawal window once unsealed - this flag is what WithdrawalRequest checks to decide whether an item is eligible, see CLAUDE.md's withdrawal_request_items note. */ ?>
    <div class="form-group mb-0">
      <label><input type="checkbox" name="is_hygiene_product" value="1" style="width:auto;" <?= !empty($product['is_hygiene_product']) ? 'checked' : '' ?>> <?= e(__('admin.product_edit.is_hygiene_product')) ?></label>
      <small style="color:var(--color-muted);display:block;"><?= e(__('admin.product_edit.is_hygiene_product_hint')) ?></small>
    </div>
  </fieldset>

  <div class="card">
    <div class="form-group mb-0">
      <label><?= e(__('admin.product_edit.images')) ?></label>
      <?php /* Image management is a separate page (products/images.php), not inline in this form, and needs a real product id to attach uploads to - so a brand-new, not-yet-saved product just gets a "save first" message instead of the link. */ ?>
      <?php if ($id): ?>
        <div>
          <a class="btn btn-secondary" href="<?= rtrim(SITE_URL, '/') ?>/admin/products/<?= (int)$id ?>/images"><?= e(__('admin.product_edit.manage_images')) ?></a>
          <span style="color:var(--color-muted);font-size:13px;margin-left:8px;">
            <?= e(__('admin.product_edit.manage_images_hint')) ?>
          </span>
        </div>
      <?php else: ?>
        <p style="color:var(--color-muted);font-size:13px;"><?= e(__('admin.product_edit.save_first_for_images')) ?></p>
      <?php endif; ?>
    </div>
  </div>

  <?php /* Hardcoded to exactly 2 option rows (e.g. "Size" and "Color") - this shop's option system supports at most two option groups per product, not an arbitrary number, so the loop below is intentionally "for ($i = 0; $i < 2; $i++)" rather than looping over $options' actual count. Each row's "values" is a single comma-separated text field (e.g. "S, M, L") that JS below explodes into the individual values used to generate variant combinations - it is NOT one input per value. */ ?>
  <fieldset>
    <legend><?= e(__('admin.product_edit.options_legend')) ?></legend>
    <p style="color:var(--color-muted);font-size:13px;margin-top:0;"><?= e(__('admin.product_edit.options_hint')) ?></p>
    <?php for ($i = 0; $i < 2; $i++): $existing = $options[$i] ?? null; ?>
      <div class="form-grid" data-option-row>
        <div class="form-group">
          <?php /* Same per-language show/hide panels as the main name/description fields above - default language edits the real option_name[] value; every other language writes to its own translations array, keyed by this option row's index ($i) since translations are matched back up to the right option row by position, not by name. */ ?>
          <?php foreach ($availableLangs as $code => $label): ?>
            <div data-lang-panel="<?= e($code) ?>" <?= $code === $defaultLang ? '' : 'style="display:none;"' ?>>
              <label><?= e(__('admin.product_edit.option_name', ['n' => $i + 1])) ?><?= $code === $defaultLang ? '' : ' (' . e($label) . ')' ?></label>
              <?php if ($code === $defaultLang): ?>
                <input type="text" name="option_name[]" placeholder="<?= e(__('admin.product_edit.option_name_placeholder')) ?>" value="<?= e($existing['name'] ?? '') ?>" oninput="scheduleVariantRegen()">
              <?php else: ?>
                <input type="text" name="option_name_translations[<?= e($code) ?>][<?= $i ?>]" placeholder="<?= e(__('admin.product_edit.option_name_placeholder')) ?>" value="<?= e($optionTranslationsForForm['names'][$i][$code] ?? '') ?>">
              <?php endif; ?>
            </div>
          <?php endforeach; ?>
        </div>
        <div class="form-group">
          <?php /* oninput="scheduleVariantRegen()" on the default-language values field is what keeps the "Variants" section further down in sync as the admin types - see scheduleVariantRegen()/regenerateVariants() in the <script> block at the bottom. Only the default-language values are used to compute variant combinations; translated values are display-only labels for those same combinations in other languages. */ ?>
          <?php foreach ($availableLangs as $code => $label): ?>
            <div data-lang-panel="<?= e($code) ?>" <?= $code === $defaultLang ? '' : 'style="display:none;"' ?>>
              <label><?= e(__('admin.product_edit.option_values')) ?><?= $code === $defaultLang ? '' : ' (' . e($label) . ')' ?></label>
              <?php if ($code === $defaultLang): ?>
                <input type="text" name="option_values[]" placeholder="<?= e(__('admin.product_edit.option_values_placeholder')) ?>"
                       value="<?= $existing ? e(implode(', ', array_column($existing['values'], 'value'))) : '' ?>" oninput="scheduleVariantRegen()">
              <?php else: ?>
                <input type="text" name="option_values_translations[<?= e($code) ?>][<?= $i ?>]" placeholder="<?= e(__('admin.product_edit.option_values_placeholder')) ?>" value="<?= e($optionTranslationsForForm['values'][$i][$code] ?? '') ?>">
              <?php endif; ?>
            </div>
          <?php endforeach; ?>
        </div>
      </div>
    <?php endfor; ?>
  </fieldset>

  <?php /* Deliberately empty on the server side (<div id="variantRows"></div>) - the actual variant rows (one per stock-tracked option combination, e.g. "Size: S, Color: Red") are generated entirely client-side by JS from the option values above, then filled in on page load from $variantStockByCombo (see the DOMContentLoaded handler in the <script> block below). This keeps this PHP template from needing to duplicate the same combination-building logic the JS already does. */ ?>
  <fieldset>
    <legend><?= e(__('admin.product_edit.variants_legend')) ?></legend>
    <p style="color:var(--color-muted);font-size:13px;margin-top:0;"><?= e(__('admin.product_edit.variants_hint')) ?></p>
    <div id="variantRows"></div>
    <button type="button" class="btn btn-sm btn-secondary" onclick="regenerateVariants(readVariantStockFromDom())"><?= e(__('admin.product_edit.regenerate_variants')) ?></button>
  </fieldset>

  <button class="btn" type="submit"><?= e(__('admin.product_edit.save')) ?></button>
  <a class="btn btn-secondary" href="<?= rtrim(SITE_URL, '/') ?>/admin/products"><?= e(__('common.cancel')) ?></a>
</form>

<script>
  // --- Client-side variant-combination builder ---
  // Turns the (up to 2) option groups' comma-separated value lists into
  // every possible combination (a Cartesian product) - e.g. Size: S,M and
  // Color: Red,Blue becomes 4 rows: S/Red, S/Blue, M/Red, M/Blue. Each
  // combination gets its own stock input (name="variant_stock[]") plus a
  // hidden field identifying which combination it is
  // (name="variant_combo[]") - the controller zips these two parallel
  // arrays back together into product_variant rows on save. See
  // CLAUDE.md's Cart section for why stock is tracked per exact
  // combination rather than per single option value.
  var initialVariantStock = <?= json_encode($variantStockByCombo, JSON_FORCE_OBJECT) ?>;
  var noOptionsMsg = <?= json_encode(__('admin.product_edit.no_options_yet')) ?>;
  var variantRowLabelSep = <?= json_encode(': ') ?>;

  // Used instead of directly concatenating untrusted strings into
  // innerHTML below - textContent-then-read-innerHTML is a safe way to
  // HTML-escape a string in the browser, mirroring what e() does in PHP.
  function escapeHtml(s) {
    var div = document.createElement('div');
    div.textContent = s;
    return div.innerHTML;
  }

  // Snapshots whatever stock numbers are CURRENTLY typed into the variant
  // rows (keyed by combo) before regenerating them, so that regenerating
  // (e.g. after editing an option's values) doesn't wipe out stock counts
  // for combinations that still exist after the edit.
  function readVariantStockFromDom() {
    var map = {};
    document.querySelectorAll('#variantRows .variant-row').forEach(function (row) {
      map[row.dataset.combo] = row.querySelector('[name="variant_stock[]"]').value;
    });
    return map;
  }

  // Rebuilds the #variantRows list from scratch based on the option name/
  // values fields' current content. `preserveStock` (a combo-key => stock
  // map, from readVariantStockFromDom() or the server-provided
  // initialVariantStock) is used to carry over stock numbers for any
  // combination that still exists after regeneration; brand-new
  // combinations start at 0.
  function regenerateVariants(preserveStock) {
    // Read both option rows' name + comma-separated values into "groups"
    // (skipping any row where the admin hasn't filled in both a name and
    // at least one value - a half-filled option row is just ignored, not
    // an error).
    var groups = [];
    document.querySelectorAll('[data-option-row]').forEach(function (row) {
      var name = row.querySelector('[name="option_name[]"]').value.trim();
      var valuesRaw = row.querySelector('[name="option_values[]"]').value.trim();
      if (!name || !valuesRaw) return;
      var values = valuesRaw.split(',').map(function (v) { return v.trim(); }).filter(function (v) { return v; });
      if (values.length) groups.push({ name: name, values: values });
    });

    var container = document.getElementById('variantRows');
    container.innerHTML = '';
    // No usable option groups at all (e.g. a simple product with no
    // options) - show a friendly message instead of an empty fieldset.
    if (!groups.length) {
      container.innerHTML = '<p style="color:var(--color-muted);font-size:13px;">' + escapeHtml(noOptionsMsg) + '</p>';
      return;
    }

    // Cartesian product: start with one "empty" combination and, for each
    // option group in turn, multiply it out by every value in that group -
    // e.g. after processing Size (S,M) then Color (Red,Blue), combos ends
    // up holding [S,Red], [S,Blue], [M,Red], [M,Blue].
    var combos = [[]];
    groups.forEach(function (group) {
      var next = [];
      combos.forEach(function (prefix) {
        group.values.forEach(function (v) {
          next.push(prefix.concat([v]));
        });
      });
      combos = next;
    });

    // Render one row per combination: a "||"-joined combo key (used both
    // as the DOM row's identity for readVariantStockFromDom() and as the
    // hidden variant_combo[] value the server reads back), a human label
    // like "Size: S, Color: Red", and a stock input prefilled from
    // preserveStock when this exact combination already had a value
    // (falls back to 0 for a brand-new combination).
    combos.forEach(function (combo, i) {
      var comboKey = combo.join('||');
      var label = combo.map(function (v, gi) { return groups[gi].name + variantRowLabelSep + v; }).join(', ');
      var stockVal = Object.prototype.hasOwnProperty.call(preserveStock, comboKey) ? preserveStock[comboKey] : '0';
      var row = document.createElement('div');
      row.className = 'form-grid variant-row';
      row.dataset.combo = comboKey;
      row.style.alignItems = 'center';
      row.innerHTML =
        '<div class="form-group" style="margin-bottom:0;">' + escapeHtml(label) + '</div>' +
        '<div class="form-group" style="margin-bottom:0;">' +
        '<input type="number" min="0" name="variant_stock[]" value="' + escapeHtml(String(stockVal)) + '">' +
        '<input type="hidden" name="variant_combo[]" value="' + escapeHtml(comboKey) + '">' +
        '</div>';
      container.appendChild(row);
    });
  }

  // Debounces regeneration while the admin is actively typing in an option
  // values field (oninput="scheduleVariantRegen()" above) - waits 600ms
  // after the last keystroke rather than rebuilding the whole variant list
  // on every single character typed.
  var variantRegenTimer = null;
  function scheduleVariantRegen() {
    clearTimeout(variantRegenTimer);
    variantRegenTimer = setTimeout(function () { regenerateVariants(readVariantStockFromDom()); }, 600);
  }

  // Build the initial variant list on page load using the stock values the
  // server already knows about ($variantStockByCombo), rather than
  // starting empty and forcing a manual "regenerate" click just to see an
  // existing product's variants.
  document.addEventListener('DOMContentLoaded', function () { regenerateVariants(initialVariantStock); });
</script>
