<?php
/**
 * Shared helper functions - v2.00 pruned. Every page-level/business-logic
 * function that used to live here has been ported into the src/ OOP stack
 * (see CLAUDE.md's architecture section); what remains below is exactly
 * the subset still called by:
 *   - install.php (the standalone first-run setup wizard, which
 *     deliberately stays outside the src/ stack - it has to work before
 *     config/installed.php, and therefore the DB the rest of the app
 *     depends on, exists at all), and
 *   - the handful of legacy classes src/container.php still loads as-is
 *     (includes/Cart.php, Mailer.php, InvoiceGenerator.php, SimplePdf.php,
 *     ImageProcessor.php, GdprTools.php, GdprCleanup.php - see CLAUDE.md's
 *     "Legacy classes kept as-is" section for why those specific classes
 *     weren't ported).
 * Nothing here is called from src/ itself - src/view-helpers.php's shims
 * delegate to the new classes, not to this file.
 */

/** Shorthand for the shared PDO database connection - every kept legacy class/query in this file and the ones that depend on it calls db() rather than constructing its own PDO instance. */
function db(): PDO
{
    return Database::getConnection();
}

/** HTML-escapes $value for safe output in a template (prevents XSS from any value that ultimately came from user input) - null-safe, so `e($maybeNullValue)` never warns. */
function e(?string $value): string
{
    return htmlspecialchars($value ?? '', ENT_QUOTES, 'UTF-8');
}

/** Formats a raw float as a display price string with the shop's currency symbol, e.g. 19.9 -> "€19,90" (German-style thousands/decimal separators - see the hardcoded ',' and '.' arguments). */
function formatPrice(float $amount): string
{
    return CURRENCY_SYMBOL . number_format($amount, 2, ',', '.');
}

/**
 * (Re)writes config/installed.php - the DB credentials + Site URL that
 * make up an installed site. Used by install.php on first setup. (Admin ->
 * Settings' equivalent is now Controllers\Admin\SettingsAdminController::
 * writeInstalledConfigFile(), a byte-for-byte port of this same function -
 * kept separate rather than shared, since install.php runs before the
 * src/ autoloader's dependencies - config/database.php, a DB connection -
 * are guaranteed to exist.)
 */
function writeInstalledConfigFile(string $host, string $port, string $name, string $user, string $pass, string $siteUrl): bool
{
    // var_export() turns each value into valid PHP source representing
    // that exact string (with correct quoting/escaping), so the generated
    // file is safe to write even if e.g. the DB password contains a quote
    // character.
    $content = "<?php\n"
        . "// Generated by install.php / Admin -> Settings on " . date('c') . ".\n"
        . "// Contains your database password - keep this file private (already in .gitignore).\n"
        . "define('DB_HOST', " . var_export($host, true) . ");\n"
        . "define('DB_PORT', " . var_export($port, true) . ");\n"
        . "define('DB_NAME', " . var_export($name, true) . ");\n"
        . "define('DB_USER', " . var_export($user, true) . ");\n"
        . "define('DB_PASS', " . var_export($pass, true) . ");\n"
        . "define('SITE_URL', " . var_export(rtrim($siteUrl, '/'), true) . ");\n";
    return file_put_contents(SHOPREX_INSTALLED_FILE, $content) !== false;
}

/** Used by install.php only - every other page redirects via Core\Response::redirect(). */
function redirect(string $path): void
{
    header('Location: ' . $path);
    exit;
}

// ---------------------------------------------------------------
// CSRF protection - install.php only (every other page's CSRF handling
// goes through Core\Csrf, a separate, unrelated implementation bound to
// the same $_SESSION['csrf_token'] key so a token from one still verifies
// against the other during the brief window install.php can still run).
// ---------------------------------------------------------------

/** Returns the current session's CSRF token, generating and storing a fresh cryptographically-random one the first time it's needed. */
function csrfToken(): string
{
    if (empty($_SESSION['csrf_token'])) {
        $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
    }
    return $_SESSION['csrf_token'];
}

/** Renders the hidden form field install.php's <form>s embed so their POST submission carries the CSRF token back for verifyCsrf()/requireCsrf() to check. */
function csrfField(): string
{
    return '<input type="hidden" name="csrf_token" value="' . e(csrfToken()) . '">';
}

/** True if the current POST request's csrf_token field matches this session's expected token - install.php's guard against cross-site request forgery on its setup forms. */
function verifyCsrf(): bool
{
    $token = $_POST['csrf_token'] ?? '';
    $sessionToken = $_SESSION['csrf_token'] ?? '';
    // Both sides must be a non-empty string before comparing - hash_equals('', '')
    // returns true, which would let a forged request with no token field pass
    // whenever the victim's session happens not to have generated one yet.
    // hash_equals() itself (rather than ===) is used for a timing-safe
    // comparison, so an attacker can't guess the token one byte at a time
    // by measuring how long the comparison takes to fail.
    return is_string($token) && $token !== '' && $sessionToken !== '' && hash_equals($sessionToken, $token);
}

/** Enforces verifyCsrf(), immediately halting the request with a 403 response if the check fails - call this at the top of any install.php POST handler. */
function requireCsrf(): void
{
    if (!verifyCsrf()) {
        http_response_code(403);
        die('Invalid or expired form submission (CSRF check failed). Please go back and try again.');
    }
}

// ---------------------------------------------------------------
// Settings (key/value store, cached per request) - still the read path
// for every kept legacy class (Mailer/InvoiceGenerator/Cart all call this
// directly); Services\SettingsRepository is the src/ equivalent everything
// else uses.
// ---------------------------------------------------------------

/**
 * Reads one row from the `settings` key/value table, or $default if that
 * key doesn't exist. Caches every setting in a function-local static
 * array on first call, so repeated getSetting() calls within the same
 * request only hit the database once - the tradeoff (documented in
 * CLAUDE.md) is that this cache can go stale if something writes a
 * setting mid-request; the legacy classes that use this function only
 * ever read settings, so that's not a problem for them in practice.
 */
function getSetting(string $key, ?string $default = null): ?string
{
    static $cache = null;
    if ($cache === null) {
        // First call this request - load every setting row once rather
        // than querying per-key, since most pages read several settings.
        $cache = [];
        $stmt = db()->query('SELECT setting_key, setting_value FROM settings');
        foreach ($stmt->fetchAll() as $row) {
            $cache[$row['setting_key']] = $row['setting_value'];
        }
    }
    return $cache[$key] ?? $default;
}

// ---------------------------------------------------------------
// Product/option translations (Admin -> Products -> edit). Cart.php calls
// applyProductTranslation() to re-derive a translated name/description for
// whatever's in $_SESSION['cart'] on every read - Services\TranslationOverlay
// is the src/ equivalent for everything else.
// ---------------------------------------------------------------

/**
 * Overlays $lang's translation onto $product - per field (name/
 * short_description/description), falling back to $product's own
 * base-language value whenever that field has no translation or the
 * translation is blank. A no-op when $lang is the site's default
 * language, since the base columns already hold exactly that.
 */
function applyProductTranslation(array $product, ?string $lang = null): array
{
    // Default to the current visitor's language when the caller doesn't
    // specify one explicitly (Cart.php passes it explicitly since it
    // already resolved it once for the whole cart).
    $lang = $lang ?? getCurrentLanguage();
    // Nothing to overlay for a product that isn't a real saved row (no id),
    // or when $lang IS the site's default language - the base columns
    // already hold exactly that language's text in that case.
    if (empty($product['id']) || $lang === getSetting('default_language', 'en')) {
        return $product;
    }

    $stmt = db()->prepare(
        'SELECT name, short_description, description FROM product_translations WHERE product_id = ? AND language = ?'
    );
    $stmt->execute([$product['id'], $lang]);
    $translation = $stmt->fetch();
    if ($translation) {
        // Field-by-field fallback: only overwrite a field if this
        // language's translation actually has a non-empty value for it -
        // an admin who translated the name but left the description blank
        // still gets the base-language description shown, not a blank one.
        foreach (['name', 'short_description', 'description'] as $field) {
            if (!empty($translation[$field])) {
                $product[$field] = $translation[$field];
            }
        }
    }
    return $product;
}

// ---------------------------------------------------------------
// Discount / VAT / tax - Cart.php needs the net effective price and tax
// rate for each line item; InvoiceGenerator needs the formatted tax
// number for its PDF columns. Services\DiscountCalculator/TaxCalculator
// are the src/ equivalents for everything else.
// ---------------------------------------------------------------

/** Active discount for $product right now, or null - internal to getEffectivePrice(). */
function getActiveDiscount(array $product): ?array
{
    $type = $product['discount_type'] ?? 'none';
    // No discount configured at all, or a discount_value of 0/empty -
    // nothing to compute.
    if ($type === 'none' || empty($product['discount_value'])) {
        return null;
    }

    // A discount can be scheduled to start/end at specific times (Admin ->
    // Products -> edit) - outside that window, it simply isn't active yet
    // or has expired, so behave exactly as if no discount existed.
    $now = new DateTimeImmutable();
    if (!empty($product['discount_starts_at']) && $now < new DateTimeImmutable($product['discount_starts_at'])) {
        return null;
    }
    if (!empty($product['discount_ends_at']) && $now > new DateTimeImmutable($product['discount_ends_at'])) {
        return null;
    }

    $price = (float)$product['price'];
    $value = (float)$product['discount_value'];
    // Two discount shapes: a percentage off (capped at 100% so a
    // misconfigured >100 value can never make the price negative), or a
    // flat amount off (capped at 0 for the same reason).
    $discounted = $type === 'percent'
        ? $price * (1 - min($value, 100) / 100)
        : max(0, $price - $value);

    return [
        'type'       => $type,
        'value'      => $value,
        'price'      => round($discounted, 2),
        // Human-readable badge text, e.g. "20% off" or "Save €5.00" -
        // translated via the site's i18n system since this is shown
        // directly on storefront product listings.
        'label'      => $type === 'percent'
            ? __('discount.percent_off', ['value' => formatTaxRateNumber($value)])
            : __('discount.save_amount', ['amount' => formatPrice($value)]),
        'starts_at'  => $product['discount_starts_at'] ?? null,
        'ends_at'    => $product['discount_ends_at'] ?? null,
    ];
}

/** The price to actually charge right now - the active discount price if any, otherwise the regular price. Always NET (before tax). */
function getEffectivePrice(array $product): float
{
    $discount = getActiveDiscount($product);
    return $discount ? $discount['price'] : (float)$product['price'];
}

/** Whether VAT/tax is turned on for the whole shop (Admin -> Settings) - when off, getTaxRatePercent() below always returns 0 regardless of any product's own tax rate. */
function vatIsEnabled(): bool
{
    return getSetting('vat_enabled', '1') === '1';
}

/**
 * Percentage to apply for $product right now - 0 whenever VAT is disabled
 * system-wide. Expects a tax_rate_percent column on $product (join/subquery
 * against tax_rates by tax_rate_id).
 */
function getTaxRatePercent(array $product): float
{
    if (!vatIsEnabled()) {
        return 0.0;
    }
    return isset($product['tax_rate_percent']) ? (float)$product['tax_rate_percent'] : 0.0;
}

/** "19" not "19.00" - trims trailing zeros for compact display like "19% off". */
function formatTaxRateNumber(float $rate): string
{
    // number_format first guarantees exactly 2 decimals (e.g. "19.00" or
    // "19.50"), then the two rtrim() calls strip trailing zeros and,
    // if nothing but zeros remained after the decimal point, the now-
    // trailing "." itself - turning "19.00" into "19" but leaving
    // "19.50" as "19.5".
    return rtrim(rtrim(number_format($rate, 2), '0'), '.');
}

/** Display URL for a product's primary image - Cart.php's cart-line thumbnail. */
function getPrimaryImage(array $product): string
{
    // Prefer the admin-cropped version of the primary image if one exists
    // (see includes/ImageProcessor.php), then the uncropped original,
    // then finally a generic placeholder graphic so a product with no
    // image at all never renders a broken <img>.
    if (!empty($product['primary_cropped_image'])) {
        return UPLOAD_URL . $product['primary_cropped_image'];
    }
    if (!empty($product['primary_image'])) {
        return UPLOAD_URL . $product['primary_image'];
    }
    return rtrim(SITE_URL, '/') . '/assets/img/placeholder.svg';
}
