<?php
/**
 * Shared helper functions - v2.00 pruned. Every page-level/business-logic
 * function that used to live here has been ported into the src/ OOP stack
 * (see CLAUDE.md's architecture section); what remains below is exactly
 * the subset still called by:
 *   - install.php (the standalone first-run setup wizard, which
 *     deliberately stays outside the src/ stack - it has to work before
 *     config/installed.php, and therefore the DB the rest of the app
 *     depends on, exists at all), and
 *   - the handful of legacy classes src/container.php still loads as-is
 *     (includes/Cart.php, Mailer.php, InvoiceGenerator.php, SimplePdf.php,
 *     ImageProcessor.php, GdprTools.php, GdprCleanup.php,
 *     PaymentGateway.php - see that file's docblock for why those specific
 *     classes weren't ported).
 * Nothing here is called from src/ itself - src/view-helpers.php's shims
 * delegate to the new classes, not to this file.
 */

function db(): PDO
{
    return Database::getConnection();
}

function e(?string $value): string
{
    return htmlspecialchars($value ?? '', ENT_QUOTES, 'UTF-8');
}

function formatPrice(float $amount): string
{
    return CURRENCY_SYMBOL . number_format($amount, 2, ',', '.');
}

/**
 * (Re)writes config/installed.php - the DB credentials + Site URL that
 * make up an installed site. Used by install.php on first setup. (Admin ->
 * Settings' equivalent is now Controllers\Admin\SettingsAdminController::
 * writeInstalledConfigFile(), a byte-for-byte port of this same function -
 * kept separate rather than shared, since install.php runs before the
 * src/ autoloader's dependencies - config/database.php, a DB connection -
 * are guaranteed to exist.)
 */
function writeInstalledConfigFile(string $host, string $port, string $name, string $user, string $pass, string $siteUrl): bool
{
    $content = "<?php\n"
        . "// Generated by install.php / Admin -> Settings on " . date('c') . ".\n"
        . "// Contains your database password - keep this file private (already in .gitignore).\n"
        . "define('DB_HOST', " . var_export($host, true) . ");\n"
        . "define('DB_PORT', " . var_export($port, true) . ");\n"
        . "define('DB_NAME', " . var_export($name, true) . ");\n"
        . "define('DB_USER', " . var_export($user, true) . ");\n"
        . "define('DB_PASS', " . var_export($pass, true) . ");\n"
        . "define('SITE_URL', " . var_export(rtrim($siteUrl, '/'), true) . ");\n";
    return file_put_contents(SHOPREX_INSTALLED_FILE, $content) !== false;
}

/** Used by install.php only - every other page redirects via Core\Response::redirect(). */
function redirect(string $path): void
{
    header('Location: ' . $path);
    exit;
}

// ---------------------------------------------------------------
// CSRF protection - install.php only (every other page's CSRF handling
// goes through Core\Csrf, a separate, unrelated implementation bound to
// the same $_SESSION['csrf_token'] key so a token from one still verifies
// against the other during the brief window install.php can still run).
// ---------------------------------------------------------------
function csrfToken(): string
{
    if (empty($_SESSION['csrf_token'])) {
        $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
    }
    return $_SESSION['csrf_token'];
}

function csrfField(): string
{
    return '<input type="hidden" name="csrf_token" value="' . e(csrfToken()) . '">';
}

function verifyCsrf(): bool
{
    $token = $_POST['csrf_token'] ?? '';
    $sessionToken = $_SESSION['csrf_token'] ?? '';
    // Both sides must be a non-empty string before comparing - hash_equals('', '')
    // returns true, which would let a forged request with no token field pass
    // whenever the victim's session happens not to have generated one yet.
    return is_string($token) && $token !== '' && $sessionToken !== '' && hash_equals($sessionToken, $token);
}

function requireCsrf(): void
{
    if (!verifyCsrf()) {
        http_response_code(403);
        die('Invalid or expired form submission (CSRF check failed). Please go back and try again.');
    }
}

// ---------------------------------------------------------------
// Settings (key/value store, cached per request) - still the read path
// for every kept legacy class (Mailer/InvoiceGenerator/PaymentGateway/
// Cart all call this directly); Services\SettingsRepository is the src/
// equivalent everything else uses.
// ---------------------------------------------------------------
function getSetting(string $key, ?string $default = null): ?string
{
    static $cache = null;
    if ($cache === null) {
        $cache = [];
        $stmt = db()->query('SELECT setting_key, setting_value FROM settings');
        foreach ($stmt->fetchAll() as $row) {
            $cache[$row['setting_key']] = $row['setting_value'];
        }
    }
    return $cache[$key] ?? $default;
}

// ---------------------------------------------------------------
// Product/option translations (Admin -> Products -> edit). Cart.php calls
// applyProductTranslation() to re-derive a translated name/description for
// whatever's in $_SESSION['cart'] on every read - Services\TranslationOverlay
// is the src/ equivalent for everything else.
// ---------------------------------------------------------------

/**
 * Overlays $lang's translation onto $product - per field (name/
 * short_description/description), falling back to $product's own
 * base-language value whenever that field has no translation or the
 * translation is blank. A no-op when $lang is the site's default
 * language, since the base columns already hold exactly that.
 */
function applyProductTranslation(array $product, ?string $lang = null): array
{
    $lang = $lang ?? getCurrentLanguage();
    if (empty($product['id']) || $lang === getSetting('default_language', 'en')) {
        return $product;
    }

    $stmt = db()->prepare(
        'SELECT name, short_description, description FROM product_translations WHERE product_id = ? AND language = ?'
    );
    $stmt->execute([$product['id'], $lang]);
    $translation = $stmt->fetch();
    if ($translation) {
        foreach (['name', 'short_description', 'description'] as $field) {
            if (!empty($translation[$field])) {
                $product[$field] = $translation[$field];
            }
        }
    }
    return $product;
}

// ---------------------------------------------------------------
// Discount / VAT / tax - Cart.php needs the net effective price and tax
// rate for each line item; InvoiceGenerator needs the formatted tax
// number for its PDF columns. Services\DiscountCalculator/TaxCalculator
// are the src/ equivalents for everything else.
// ---------------------------------------------------------------

/** Active discount for $product right now, or null - internal to getEffectivePrice(). */
function getActiveDiscount(array $product): ?array
{
    $type = $product['discount_type'] ?? 'none';
    if ($type === 'none' || empty($product['discount_value'])) {
        return null;
    }

    $now = new DateTimeImmutable();
    if (!empty($product['discount_starts_at']) && $now < new DateTimeImmutable($product['discount_starts_at'])) {
        return null;
    }
    if (!empty($product['discount_ends_at']) && $now > new DateTimeImmutable($product['discount_ends_at'])) {
        return null;
    }

    $price = (float)$product['price'];
    $value = (float)$product['discount_value'];
    $discounted = $type === 'percent'
        ? $price * (1 - min($value, 100) / 100)
        : max(0, $price - $value);

    return [
        'type'       => $type,
        'value'      => $value,
        'price'      => round($discounted, 2),
        'label'      => $type === 'percent'
            ? __('discount.percent_off', ['value' => formatTaxRateNumber($value)])
            : __('discount.save_amount', ['amount' => formatPrice($value)]),
        'starts_at'  => $product['discount_starts_at'] ?? null,
        'ends_at'    => $product['discount_ends_at'] ?? null,
    ];
}

/** The price to actually charge right now - the active discount price if any, otherwise the regular price. Always NET (before tax). */
function getEffectivePrice(array $product): float
{
    $discount = getActiveDiscount($product);
    return $discount ? $discount['price'] : (float)$product['price'];
}

function vatIsEnabled(): bool
{
    return getSetting('vat_enabled', '1') === '1';
}

/**
 * Percentage to apply for $product right now - 0 whenever VAT is disabled
 * system-wide. Expects a tax_rate_percent column on $product (join/subquery
 * against tax_rates by tax_rate_id).
 */
function getTaxRatePercent(array $product): float
{
    if (!vatIsEnabled()) {
        return 0.0;
    }
    return isset($product['tax_rate_percent']) ? (float)$product['tax_rate_percent'] : 0.0;
}

/** "19" not "19.00" - trims trailing zeros for compact display like "19% off". */
function formatTaxRateNumber(float $rate): string
{
    return rtrim(rtrim(number_format($rate, 2), '0'), '.');
}

/** Display URL for a product's primary image - Cart.php's cart-line thumbnail. */
function getPrimaryImage(array $product): string
{
    if (!empty($product['primary_cropped_image'])) {
        return UPLOAD_URL . $product['primary_cropped_image'];
    }
    if (!empty($product['primary_image'])) {
        return UPLOAD_URL . $product['primary_image'];
    }
    return rtrim(SITE_URL, '/') . '/assets/img/placeholder.svg';
}
